

import com.github.javafaker.Faker;
import Class.ConnectionProvider;
import javax.swing.*;
import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class HelpDeskPage extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationPage
     */
    public HelpDeskPage() {
        initComponents();        
    }

    //Generate Random Username
    private String setUsername() {
        return null;
    }
    
    //Reset the form
    private void resetForm() {
        firstNameField_.setText(null);
        middleNameField_.setText(null);
        lastNameField_.setText(null);
        fatherNameField_.setText(null);
        dobField_.setCalendar(null);
        genderField_.setSelectedIndex(0);
        addressField_.setText(null);
        phoneNumberField_.setText(null);
        eMailIdField_.setText(null);
        usernameField_.setText(null);
        weightField_.setText(null);
        heightField_.setText(null);
        bloodGroupField_.setSelectedIndex(0);
    }
    

    //Change color of selected Button 
    private void changeButtonAndIcon(JButton btn, String iconname){
        Color defaultColor = new Color(197,205,214);
        
        dashBoardTab_.setForeground(defaultColor);
        addPatientTab_.setForeground(defaultColor);
        managePatientTab_.setForeground(defaultColor);
        patientHistorytab_.setForeground(defaultColor);
        labReportTab_.setForeground(defaultColor);
        sendAmbulanceTab_.setForeground(defaultColor);
        
        dashBoardTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png")));
        addPatientTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png")));
        managePatientTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage.png")));
        patientHistorytab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png")));
        labReportTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png")));
        sendAmbulanceTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ambulance.png")));
        
        btn.setForeground(Color.cyan);
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+iconname+"_selected.png")));
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBarPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashBoardTab_ = new javax.swing.JButton();
        addPatientTab_ = new javax.swing.JButton();
        managePatientTab_ = new javax.swing.JButton();
        patientHistorytab_ = new javax.swing.JButton();
        labReportTab_ = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        sendAmbulanceTab_ = new javax.swing.JButton();
        userDP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        closeButton_ = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        addPatientPanel_ = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstNameField_ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        middleNameField_ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lastNameField_ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fatherNameField_ = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        genderField_ = new javax.swing.JComboBox<>();
        addressField_ = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phoneNumberField_ = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        weightField_ = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        heightField_ = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bloodGroupField_ = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        insuranceCompanyField_ = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        policyNumberField_ = new javax.swing.JTextField();
        addPatientButton_ = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        eMailIdField_ = new javax.swing.JTextField();
        usernameField_ = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        dobField_ = new com.toedter.calendar.JDateChooser();
        resetButton_ = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        dashBoardPanel_ = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBarPanel.setBackground(new java.awt.Color(39, 36, 142));
        navBarPanel.setPreferredSize(new java.awt.Dimension(250, 800));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("General Hospital");

        dashBoardTab_.setBackground(new java.awt.Color(39, 36, 142));
        dashBoardTab_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashBoardTab_.setForeground(new java.awt.Color(197, 205, 214));
        dashBoardTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        dashBoardTab_.setText(" DASHBOARD");
        dashBoardTab_.setToolTipText("");
        dashBoardTab_.setBorder(null);
        dashBoardTab_.setContentAreaFilled(false);
        dashBoardTab_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashBoardTab_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashBoardTab_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashBoardTab_ActionPerformed(evt);
            }
        });

        addPatientTab_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addPatientTab_.setForeground(new java.awt.Color(197, 205, 214));
        addPatientTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        addPatientTab_.setText(" ADD PATIENT");
        addPatientTab_.setBorder(null);
        addPatientTab_.setContentAreaFilled(false);
        addPatientTab_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addPatientTab_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientTab_ActionPerformed(evt);
            }
        });

        managePatientTab_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        managePatientTab_.setForeground(new java.awt.Color(197, 205, 214));
        managePatientTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage.png"))); // NOI18N
        managePatientTab_.setText(" MANAGE PATIENT");
        managePatientTab_.setBorder(null);
        managePatientTab_.setContentAreaFilled(false);
        managePatientTab_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        managePatientTab_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientTab_ActionPerformed(evt);
            }
        });

        patientHistorytab_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientHistorytab_.setForeground(new java.awt.Color(197, 205, 214));
        patientHistorytab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        patientHistorytab_.setText(" PATIENT HISTORY");
        patientHistorytab_.setBorder(null);
        patientHistorytab_.setContentAreaFilled(false);
        patientHistorytab_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        patientHistorytab_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHistorytab_ActionPerformed(evt);
            }
        });

        labReportTab_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labReportTab_.setForeground(new java.awt.Color(197, 205, 214));
        labReportTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        labReportTab_.setText(" LAB REPORT");
        labReportTab_.setBorder(null);
        labReportTab_.setContentAreaFilled(false);
        labReportTab_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labReportTab_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labReportTab_ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(23, 128, 222));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jButton6.setContentAreaFilled(false);
        jButton6.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        sendAmbulanceTab_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendAmbulanceTab_.setForeground(new java.awt.Color(197, 205, 214));
        sendAmbulanceTab_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ambulance.png"))); // NOI18N
        sendAmbulanceTab_.setText(" SEND AMBULANCE");
        sendAmbulanceTab_.setBorder(null);
        sendAmbulanceTab_.setContentAreaFilled(false);
        sendAmbulanceTab_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sendAmbulanceTab_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAmbulanceTab_ActionPerformed(evt);
            }
        });

        userDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/helpdesk.png"))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(197, 194, 200));
        jLabel3.setText("@username");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(197, 194, 200));
        jLabel6.setText("NAME HERE");

        jButton7.setBackground(new java.awt.Color(23, 128, 222));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jButton7.setContentAreaFilled(false);
        jButton7.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        closeButton_.setBackground(new java.awt.Color(255, 30, 0));
        closeButton_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeButton_.setForeground(new java.awt.Color(255, 255, 255));
        closeButton_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeButton_.setToolTipText("");
        closeButton_.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 0)));
        closeButton_.setContentAreaFilled(false);
        closeButton_.setPreferredSize(new java.awt.Dimension(73, 30));
        closeButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton_ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(23, 128, 222));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userSettings.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jButton8.setContentAreaFilled(false);
        jButton8.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ANGELSTONE");

        javax.swing.GroupLayout navBarPanelLayout = new javax.swing.GroupLayout(navBarPanel);
        navBarPanel.setLayout(navBarPanelLayout);
        navBarPanelLayout.setHorizontalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navBarPanelLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(closeButton_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dashBoardTab_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPatientTab_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managePatientTab_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(patientHistorytab_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(navBarPanelLayout.createSequentialGroup()
                            .addComponent(userDP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(sendAmbulanceTab_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labReportTab_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        navBarPanelLayout.setVerticalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6))
                    .addComponent(userDP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(dashBoardTab_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(addPatientTab_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(managePatientTab_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(patientHistorytab_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labReportTab_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(sendAmbulanceTab_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(navBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        parentPanel.setLayout(new java.awt.CardLayout());

        addPatientPanel_.setBackground(new java.awt.Color(226, 235, 241));
        addPatientPanel_.setPreferredSize(new java.awt.Dimension(1050, 800));

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 69, 83));
        jLabel5.setText("ADD PATIENT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 69, 83));
        jLabel4.setText("FIRST NAME");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 20));

        firstNameField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstNameField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstNameField_.setToolTipText("");
        firstNameField_.setBorder(null);
        firstNameField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(62, 69, 83));
        jLabel7.setText("MIDDLE NAME");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 20));

        middleNameField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        middleNameField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        middleNameField_.setToolTipText("");
        middleNameField_.setBorder(null);
        middleNameField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(62, 69, 83));
        jLabel8.setText("LAST NAME");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 20));

        lastNameField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastNameField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastNameField_.setToolTipText("");
        lastNameField_.setBorder(null);
        lastNameField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(62, 69, 83));
        jLabel9.setText("FATHER'S NAME");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 20));

        fatherNameField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fatherNameField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fatherNameField_.setToolTipText("");
        fatherNameField_.setBorder(null);
        fatherNameField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(62, 69, 83));
        jLabel11.setText("GENDER");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 20));

        genderField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderField_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-- SELECT -->", "MALE", "FEMALE", "OTHER" }));

        addressField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addressField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addressField_.setToolTipText("");
        addressField_.setBorder(null);
        addressField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(62, 69, 83));
        jLabel12.setText("PERMANENT ADDRESS ");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(62, 69, 83));
        jLabel13.setText("DATE OF BIRTH");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 20));

        phoneNumberField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phoneNumberField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneNumberField_.setToolTipText("");
        phoneNumberField_.setBorder(null);
        phoneNumberField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(62, 69, 83));
        jLabel14.setText("PHONE NO");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(62, 69, 83));
        jLabel15.setText("WEIGHT");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 20));

        weightField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        weightField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        weightField_.setToolTipText("");
        weightField_.setBorder(null);
        weightField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(62, 69, 83));
        jLabel16.setText("HEIGHT");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 20));

        heightField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        heightField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        heightField_.setToolTipText("");
        heightField_.setBorder(null);
        heightField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(62, 69, 83));
        jLabel17.setText("BLOOD GROUP");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 20));

        bloodGroupField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bloodGroupField_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-- SELECT -->", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(62, 69, 83));
        jLabel18.setText("INSURANCE COMPANY");
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 20));

        insuranceCompanyField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insuranceCompanyField_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-- SELECT -->", "RELIGARE", "MAX BUPA", "BHARTI AXA", "BAJAJ ALLIANZ" }));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(62, 69, 83));
        jLabel19.setText("POLICY NUMBER");
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 20));

        policyNumberField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        policyNumberField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        policyNumberField_.setToolTipText("");
        policyNumberField_.setBorder(null);
        policyNumberField_.setPreferredSize(new java.awt.Dimension(250, 35));

        addPatientButton_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addPatientButton_.setText("ADD");
        addPatientButton_.setPreferredSize(new java.awt.Dimension(100, 30));
        addPatientButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButton_ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(62, 69, 83));
        jLabel20.setText("EMAIL ID");
        jLabel20.setPreferredSize(new java.awt.Dimension(100, 20));

        eMailIdField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eMailIdField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        eMailIdField_.setToolTipText("");
        eMailIdField_.setBorder(null);
        eMailIdField_.setPreferredSize(new java.awt.Dimension(250, 35));

        usernameField_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameField_.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField_.setToolTipText("");
        usernameField_.setBorder(null);
        usernameField_.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(62, 69, 83));
        jLabel21.setText("USERNAME");
        jLabel21.setPreferredSize(new java.awt.Dimension(100, 20));

        dobField_.setBackground(new java.awt.Color(51, 51, 51));
        dobField_.setForeground(new java.awt.Color(255, 255, 255));
        dobField_.setDateFormatString("dd-mm-yyyy");

        resetButton_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetButton_.setText("RESET");
        resetButton_.setPreferredSize(new java.awt.Dimension(100, 30));
        resetButton_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPatientPanel_Layout = new javax.swing.GroupLayout(addPatientPanel_);
        addPatientPanel_.setLayout(addPatientPanel_Layout);
        addPatientPanel_Layout.setHorizontalGroup(
            addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPatientPanel_Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanel_Layout.createSequentialGroup()
                                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(weightField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(75, 75, 75)
                                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(heightField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(policyNumberField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(eMailIdField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumberField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bloodGroupField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                    .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fatherNameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(75, 75, 75)
                                    .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(middleNameField_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dobField_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(75, 75, 75)
                                    .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastNameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genderField_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addressField_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                .addComponent(resetButton_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(addPatientButton_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPatientPanel_Layout.createSequentialGroup()
                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insuranceCompanyField_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(75, 75, 75))
        );
        addPatientPanel_Layout.setVerticalGroup(
            addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addPatientPanel_Layout.createSequentialGroup()
                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(middleNameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(firstNameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lastNameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(fatherNameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPatientPanel_Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(genderField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addPatientPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dobField_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGap(30, 30, 30)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addressField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addPatientPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eMailIdField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPatientPanel_Layout.createSequentialGroup()
                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGap(30, 30, 30)
                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(weightField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(heightField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bloodGroupField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPatientPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policyNumberField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insuranceCompanyField_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(addPatientPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientButton_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        parentPanel.add(addPatientPanel_, "card2");
        addPatientPanel_.getAccessibleContext().setAccessibleName("");

        dashBoardPanel_.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout dashBoardPanel_Layout = new javax.swing.GroupLayout(dashBoardPanel_);
        dashBoardPanel_.setLayout(dashBoardPanel_Layout);
        dashBoardPanel_Layout.setHorizontalGroup(
            dashBoardPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        dashBoardPanel_Layout.setVerticalGroup(
            dashBoardPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        parentPanel.add(dashBoardPanel_, "card2");

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1050, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void labReportTab_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labReportTab_ActionPerformed
        // TODO add your handling code here:
        changeButtonAndIcon(labReportTab_, "report");
    }//GEN-LAST:event_labReportTab_ActionPerformed

    private void patientHistorytab_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHistorytab_ActionPerformed
        // TODO add your handling code here:
        changeButtonAndIcon(patientHistorytab_, "history");
    }//GEN-LAST:event_patientHistorytab_ActionPerformed

    private void managePatientTab_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientTab_ActionPerformed
        // TODO add your handling code here:
        changeButtonAndIcon(managePatientTab_, "manage");
        parentPanel.removeAll();
       // parentPanel.add(managePatientPanel_);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_managePatientTab_ActionPerformed

    private void addPatientTab_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientTab_ActionPerformed
        // TODO add your handling code here:
        changeButtonAndIcon(addPatientTab_, "addUser");
        parentPanel.removeAll();
        parentPanel.add(addPatientPanel_);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_addPatientTab_ActionPerformed

    private void dashBoardTab_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashBoardTab_ActionPerformed
        // TODO add your handling code here:
        changeButtonAndIcon(dashBoardTab_, "dashboard");
        parentPanel.removeAll();
        parentPanel.add(dashBoardPanel_);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_dashBoardTab_ActionPerformed

    private void sendAmbulanceTab_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAmbulanceTab_ActionPerformed
        // TODO add your handling code here:
        changeButtonAndIcon(sendAmbulanceTab_, "ambulance");
    }//GEN-LAST:event_sendAmbulanceTab_ActionPerformed

    private void addPatientButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButton_ActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameField_.getText();
        String middleName = middleNameField_.getText();
        String lastName = lastNameField_.getText();
        String fathersName = fatherNameField_.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("DD-MM-YYYY");
        String dateofBirth = sdf.format(dobField_.getDate());
        String gender = (String)genderField_.getSelectedItem();
        String address = addressField_.getText();
        String phoneNum = phoneNumberField_.getText();
        String eMailID = eMailIdField_.getText();
        String username = usernameField_.getText();
        String weight = weightField_.getText();
        String height = heightField_.getText();
        String bloodGroup = (String)bloodGroupField_.getSelectedItem();
        String insuranceCompany = (String)insuranceCompanyField_.getSelectedItem();
        String policyNo = policyNumberField_.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into PATIENT(FIRST_NAME, MIDDLE_NAME,  LAST_NAME, FATHERS_NAME, DATE_OF_BIRTH, GENDER, ADDRESS, PHONE_NO, EMAIL_ID, USERNAME, WEIGHT,  HEIGHT, BLOOD_GROUP, INSURANCE_COMPANY, POLICY_NO) values('"+firstName+"' , '"+middleName+"', '"+lastName+"', '"+fathersName+"', '"+dateofBirth+"', '"+gender+"', '"+address+"', '"+phoneNum+"', '"+eMailID+"', '"+username+"', '"+weight+"' , '"+height+"',  '"+bloodGroup+"' , '"+insuranceCompany+"', '"+policyNo+"')");
            JOptionPane.showInternalConfirmDialog(null, "PATIENT ADDED SUCCESSFULLY", "ADD PATIENT",JOptionPane.PLAIN_MESSAGE);
        } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
        }
        resetForm();
        
    }//GEN-LAST:event_addPatientButton_ActionPerformed

    private void resetButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton_ActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_resetButton_ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void closeButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton_ActionPerformed
        // TODO add your handling code here:
        int yesOrNo = JOptionPane.showInternalConfirmDialog(null, "CLOSE THE APPLICATION", "ALERT!", JOptionPane.YES_NO_OPTION);
        if(yesOrNo==0) System.exit(0);
    }//GEN-LAST:event_closeButton_ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpDeskPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpDeskPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientButton_;
    private javax.swing.JPanel addPatientPanel_;
    private javax.swing.JButton addPatientTab_;
    private javax.swing.JTextField addressField_;
    private javax.swing.JComboBox<String> bloodGroupField_;
    private javax.swing.JButton closeButton_;
    private javax.swing.JPanel dashBoardPanel_;
    private javax.swing.JButton dashBoardTab_;
    private com.toedter.calendar.JDateChooser dobField_;
    private javax.swing.JTextField eMailIdField_;
    private javax.swing.JTextField fatherNameField_;
    private javax.swing.JTextField firstNameField_;
    private javax.swing.JComboBox<String> genderField_;
    private javax.swing.JTextField heightField_;
    private javax.swing.JComboBox<String> insuranceCompanyField_;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton labReportTab_;
    private javax.swing.JTextField lastNameField_;
    private javax.swing.JButton managePatientTab_;
    private javax.swing.JTextField middleNameField_;
    private javax.swing.JPanel navBarPanel;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JButton patientHistorytab_;
    private javax.swing.JTextField phoneNumberField_;
    private javax.swing.JTextField policyNumberField_;
    private javax.swing.JButton resetButton_;
    private javax.swing.JButton sendAmbulanceTab_;
    private javax.swing.JLabel userDP;
    private javax.swing.JTextField usernameField_;
    private javax.swing.JTextField weightField_;
    // End of variables declaration//GEN-END:variables

    
}
